***class name always starts with upper case is called as pascel conversion.
***in array every box is called as bucket.
***within static method we cannot use this and super key.
***global and local variable will be differenciate by this key if having same value.
***in non static gv to non static lv we use this key.
***lv have higher priority than gv.
***genralization:-declaring same methods in all sub class to one superclass.
***specilization:-declaring specific methods in sub class.
***OBJECT:-it is an instance of a class it is mainly used to allocate memory of a class member & member Function( The object has state and behavior. )
***y constr is not static:-because as we know that constructror will work whenever the object is created object is created for non staic not foe static so...
***y constr is not final:- because constructror cannot be inherited..
*** constructor cannot be inherited:- because the subclass name is different 
*** y final cannot be inherited:- the main purpose of class being declared as final is because to prevent the classs from being subclassed.

***abstract cannot be Override so not static and final.

-->sample resume
-->friend Function
-->user input
-->enum



JRE stands for Java Runtime Environment. It is the implementation of JVM.it
is a set of libraries and other files JVM uses at runtime, which are used for developing Java applications.

Just-in-time (JIT): it is an interpreter or a part of bitecode which is user to improve the excicution.

What is the purpose of static methods and variables?
Static method reduce the amount of memory used by a program. Static variables are shared among all instances of a class.
 Non static variables are specific to that instance of a class. Static variable is like a global variable and is available to all methods.

 default constructor: is automatically generated by the compiler if no constructors have been defined for the class.
 parameterist constructor: when it accepts a specific number of parameters. To initialize data members of a class with distinct values.

 The static variable is used to refer to the common property of all objects.



